*** Settings ***
Documentation       Validates parsing of OSCAR kind deployment output without running the deploy script.

Library             OperatingSystem
Resource            ${CURDIR}/../../resources/local-kind-parsing.resource

Suite Teardown      Remove Parsing Variable File


*** Variables ***
${FIXTURE_OUTPUT}        ${CURDIR}/fixtures/kind-deploy-output.txt
${PARSING_ENV_FILE}      ${CURDIR}/kind-parsing.env.yaml


*** Test Cases ***
Parse Synthetic Deployment Output
    [Documentation]    Ensures Parse Deployment Details extracts all key fields, computes Basic auth, and writes the env file.
    Remove Parsing Variable File
    ${stdout}=    Get File    ${FIXTURE_OUTPUT}
    ${details}=    Parse Deployment Details    ${stdout}
    Should Be Equal As Strings    ${details["cluster_name"]}    oscar-test-mjn
    Should Be Equal As Strings    ${details["context"]}         kind-oscar-test-mjn
    Should Be Equal As Strings    ${details["http_url"]}        http://localhost
    Should Be Equal As Strings    ${details["https_url"]}       https://localhost
    Should Be Equal As Strings    ${details["username"]}        oscar
    Should Be Equal As Strings    ${details["password"]}        MjNkZGIw
    Should Be Equal As Strings    ${details["basic_token"]}     b3NjYXI6TWpOa1pHSXc=
    Create Parsing Variable File    ${details}
    ${env_contents}=    Get File    ${PARSING_ENV_FILE}
    Should Contain    ${env_contents}    BASIC_USER: ${details["basic_token"]}
    Should Contain    ${env_contents}    OSCAR_ENDPOINT: ${details["http_url"]}
    Should Contain    ${env_contents}    LOCAL_TESTING: True


*** Keywords ***
Create Parsing Variable File
    [Documentation]    Writes the Robot variable file using parsed deployment details.
    [Arguments]    ${details}
    ${content}=    Catenate    SEPARATOR=\n
    ...    # Generated by tests/deployment/local-kind-parsing.robot
    ...    AUTHENTICATION_PROCESS: resources/token-local.resource
    ...    OSCAR_ENDPOINT: ${details["http_url"]}
    ...    OSCAR_METRICS: ${details["http_url"]}/metrics
    ...    OSCAR_DASHBOARD: ${details["https_url"]}
    ...    BASIC_USER: ${details["basic_token"]}
    ...    AAI_GROUP: oscar
    ...    LOCAL_TESTING: True
    ...    SSL_VERIFY: False
    Create File    ${PARSING_ENV_FILE}    ${content}

Remove Parsing Variable File
    [Documentation]    Cleans the temporary env file created by the parsing test.
    ${exists}=    Run Keyword And Return Status    File Should Exist    ${PARSING_ENV_FILE}
    Run Keyword If    ${exists}    Remove File    ${PARSING_ENV_FILE}
