*** Settings ***
Documentation       Deploy a local OSCAR cluster via kind and run the core service lifecycle suite.

Library             Collections
Library             OperatingSystem
Library             Process
Library             RequestsLibrary
Library             String
Resource            ${CURDIR}/../../resources/local-kind-parsing.resource

Suite Setup         Setup Local Kind Deployment
Suite Teardown      Cleanup Local Kind Deployment


*** Variables ***
${DEPLOY_SCRIPT}                ${EMPTY}
${DEPLOY_ARGUMENTS}             --devel
${VARIABLE_FILE}                ${EXECDIR}/variables/.env-kind-local.yaml
${SERVICE_SUITE}                tests/api/service-lifecycle.robot
${RESULTS_DIR}                  ${EXECDIR}/robot_results/local-kind
${READY_RESULTS_DIR}            ${EXECDIR}/robot_results/local-kind-ready
${HEALTH_ENDPOINT}              /health
${KIND_CLUSTER_NAME}            ${EMPTY}
${KIND_CONTEXT}                 ${EMPTY}
${OSCAR_HTTP_URL}               ${EMPTY}
${OSCAR_HTTPS_URL}              ${EMPTY}
${BASIC_AUTH_TOKEN}             ${EMPTY}
${DEFAULT_AAI_GROUP}            oscar
${OSCAR_REPO_URL}               https://github.com/grycap/oscar.git
${OSCAR_REPO_BRANCH}            devel
${OSCAR_CLONE_DIR}              ${EXECDIR}/.oscar-kind
${OSCAR_WORKTREE}               ${EMPTY}
${OSCAR_CLONED}                 ${False}
${OSCAR_PATH}                   ${EMPTY}
${KEEP_CLUSTER_ON_FAILURE}      ${False}
${SERVICE_READY_MAX_ATTEMPTS}   5
${SERVICE_READY_RETRY_DELAY}    60s


*** Test Cases ***
Run Service Lifecycle Against Local Deployment
    [Documentation]    Executes the existing API/service lifecycle test suite against the freshly deployed cluster.
    Ensure Results Directory Exists
    ${result}=    Run Process    robot    -V    ${VARIABLE_FILE}    -d    ${RESULTS_DIR}    ${SERVICE_SUITE}
    ...    cwd=${EXECDIR}
    Log    ${result.stdout}
    Log    ${result.stderr}
    Should Be Equal As Integers    ${result.rc}    0


*** Keywords ***
Setup Local Kind Deployment
    [Documentation]    Runs the kind deployment script and prepares the variable file used by downstream suites.
    ${worktree}=    Determine OSCAR Repository
    Set Suite Variable    ${OSCAR_WORKTREE}    ${worktree}
    ${deploy_path}=    Join Path    ${OSCAR_WORKTREE}    deploy    kind-deploy.sh
    File Should Exist    ${deploy_path}
    Set Suite Variable    ${DEPLOY_SCRIPT}    ${deploy_path}
    Remove Local Kind Variable File
    ${result}=    Run Process    sh    ${DEPLOY_SCRIPT}    ${DEPLOY_ARGUMENTS}    cwd=${EXECDIR}
    Log    ${result.stdout}
    Log    ${result.stderr}
    Should Be Equal As Integers    ${result.rc}    0
    ${details}=    Parse Deployment Details    ${result.stdout}
    Set Suite Variable    ${KIND_CLUSTER_NAME}    ${details["cluster_name"]}
    Set Suite Variable    ${KIND_CONTEXT}         ${details["context"]}
    Set Suite Variable    ${OSCAR_HTTP_URL}       ${details["http_url"]}
    Set Suite Variable    ${OSCAR_HTTPS_URL}      ${details["https_url"]}
    Set Suite Variable    ${BASIC_AUTH_TOKEN}     ${details["basic_token"]}
    Create Kind Variable File
    Wait For OSCAR API Ready
    Wait For Service Lifecycle Ready

Cleanup Local Kind Deployment
    [Documentation]    Always attempt to delete the kind cluster and remove temporary files.
    ${skip_cleanup}=    Should Skip Cluster Cleanup
    Run Keyword If    not ${skip_cleanup} and '${KIND_CLUSTER_NAME}'    Delete Kind Cluster
    Run Keyword If    not ${skip_cleanup}    Remove Local Kind Variable File
    Run Keyword If    not ${skip_cleanup} and ${OSCAR_CLONED}    Remove OSCAR Clone
    Run Keyword If    ${skip_cleanup}    Log    Keeping cluster for investigation (KEEP_CLUSTER_ON_FAILURE=True and suite failed).    WARN

Delete Kind Cluster
    [Documentation]    Deletes the temporary kind cluster created for the test.
    ${result}=    Run Process    kind    delete    cluster    --name    ${KIND_CLUSTER_NAME}
    ...    cwd=${EXECDIR}
    Log    ${result.stdout}
    Log    ${result.stderr}
    IF    ${result.rc} != 0
        Log    Kind cluster deletion returned rc=${result.rc}    WARN
    END

Remove Local Kind Variable File
    [Documentation]    Removes the auto-generated variable file so future runs start cleanly.
    ${exists}=    Run Keyword And Return Status    File Should Exist    ${VARIABLE_FILE}
    Run Keyword If    ${exists}    Remove File    ${VARIABLE_FILE}

Ensure Results Directory Exists
    [Documentation]    Creates the directory that stores robot outputs from the downstream suite.
    Run Keyword And Ignore Error    Create Directory    ${RESULTS_DIR}

Create Kind Variable File
    [Documentation]    Writes the Robot variable file consumed by the downstream suite.
    ${content}=    Catenate    SEPARATOR=\n
    ...    # Auto-generated by tests/deployment/local-kind.robot
    ...    AUTHENTICATION_PROCESS: resources/token-local.resource
    ...    OSCAR_ENDPOINT: ${OSCAR_HTTP_URL}
    ...    OSCAR_METRICS: ${OSCAR_HTTP_URL}/metrics
    ...    OSCAR_DASHBOARD: ${OSCAR_HTTPS_URL}
    ...    BASIC_USER: ${BASIC_AUTH_TOKEN}
    ...    AAI_GROUP: ${DEFAULT_AAI_GROUP}
    ...    LOCAL_TESTING: True
    ...    SSL_VERIFY: False
    Create File    ${VARIABLE_FILE}    ${content}

Wait For OSCAR API Ready
    [Documentation]    Polls the /health endpoint until the deployment responds.
    Wait Until Keyword Succeeds    12x    15s    Check OSCAR Health

Check OSCAR Health
    [Documentation]    Performs a single HTTP call against the health endpoint.
    ${headers}=    Create Dictionary    Authorization=Basic ${BASIC_AUTH_TOKEN}
    ${response}=    GET    url=${OSCAR_HTTP_URL}${HEALTH_ENDPOINT}    headers=${headers}    verify=False
    Should Be Equal As Strings    ${response.status_code}    200

Wait For Service Lifecycle Ready
    [Documentation]    Runs the ready-tagged subset of the service lifecycle suite until it succeeds or the retry budget is exhausted.
    FOR    ${index}    IN RANGE    ${SERVICE_READY_MAX_ATTEMPTS}
        ${ready_dir}=    Join Path    ${READY_RESULTS_DIR}    attempt-${index}
        Remove Directory If Exists    ${ready_dir}
        ${result}=    Run Process    robot    -V    ${VARIABLE_FILE}    -d    ${ready_dir}    -i    ready    ${SERVICE_SUITE}
        ...    cwd=${EXECDIR}
        Log    ${result.stdout}
        Log    ${result.stderr}
        Run Keyword If    ${result.rc} == 0    Return From Keyword
        Log    Readiness attempt ${index + 1} failed (rc=${result.rc}). Waiting ${SERVICE_READY_RETRY_DELAY} before retrying.    WARN
        Sleep    ${SERVICE_READY_RETRY_DELAY}
    END
    Fail    Service lifecycle readiness check failed after ${SERVICE_READY_MAX_ATTEMPTS} attempts.

Determine OSCAR Repository
    [Documentation]    Resolves the OSCAR source directory either via user input or by cloning devel from GitHub.
    ${custom_path}=    Strip String    ${OSCAR_PATH}
    IF    '${custom_path}'
        ${provided}=    Use Provided OSCAR Path    ${custom_path}
        RETURN    ${provided}
    END
    ${cloned}=    Clone OSCAR Repository
    RETURN    ${cloned}

Use Provided OSCAR Path
    [Documentation]    Validates the user-supplied OSCAR directory contains the deploy script.
    [Arguments]    ${path}
    ${normalized}=    Normalize Path    ${path}
    ${script}=    Join Path    ${normalized}    deploy    kind-deploy.sh
    File Should Exist    ${script}
    Set Suite Variable    ${OSCAR_CLONED}    ${False}
    RETURN    ${normalized}

Clone OSCAR Repository
    [Documentation]    Clones the OSCAR repository locally so the deploy script is available.
    ${target}=    Normalize Path    ${OSCAR_CLONE_DIR}
    Run Keyword And Ignore Error    Remove Directory    ${target}    recursive=True
    ${result}=    Run Process    git    clone    --branch    ${OSCAR_REPO_BRANCH}    ${OSCAR_REPO_URL}    ${target}
    ...    stdout=True    stderr=True    cwd=${EXECDIR}
    Log    ${result.stdout}
    Log    ${result.stderr}
    Should Be Equal As Integers    ${result.rc}    0
    Set Suite Variable    ${OSCAR_CLONED}    ${True}
    RETURN    ${target}

Remove OSCAR Clone
    [Documentation]    Deletes the cloned OSCAR working tree created for the test run.
    Run Keyword And Ignore Error    Remove Directory    ${OSCAR_WORKTREE}    recursive=True

Should Skip Cluster Cleanup
    [Documentation]    Returns True when the suite failed and KEEP_CLUSTER_ON_FAILURE is enabled.
    ${suite_failed}=    Run Keyword And Return Status    Should Be Equal As Strings    ${SUITE STATUS}    FAIL
    ${skip}=    Evaluate    bool(${KEEP_CLUSTER_ON_FAILURE}) and ${suite_failed}
    RETURN    ${skip}

Remove Directory If Exists
    [Documentation]    Deletes a directory when it exists.
    [Arguments]    ${path}
    ${exists}=    Run Keyword And Return Status    Path Should Exist    ${path}
    Run Keyword If    ${exists}    Remove Directory    ${path}    recursive=True
